# Generated by Django 5.2.4 on 2025-07-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_assigned_to_alter_complaint_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
