# Generated by Django 5.2.4 on 2025-08-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
